### ISSUE TITLE
care2x not compatible to php 5

### ISSUE THREAD

**Issue by extraserve** [care2x/care2x#19]
hello there
after I have installed care2x, it is not working
http://www.darulshefaa.com/index.php

give me that error:

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php on line 365

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php:365) in /home/darulshefaa/public_html/include/core/inc_environment_global.php on line 100

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php:365) in /home/darulshefaa/public_html/include/core/inc_environment_global.php on line 100

Warning: Cannot modify header information - headers already sent by (output started at /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php:365) in /home/darulshefaa/public_html/index.php on line 140

Warning: Cannot modify header information - headers already sent by (output started at /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php:365) in /home/darulshefaa/public_html/index.php on line 298

I understood it is not compatible with php 5

any help for that please?

**Comment by sovello** [comment]
Care2x now supports PHP 7 as the default PHP version. You may need to
install PHP 7 on your server for Care2x to run.

Cheers

2016-06-16 6:47 GMT+03:00 extraserve <notifications@github.com>:

> hello there
> after I have installed care2x, it is not working
> http://www.darulshefaa.com/index.php
>
> give me that error:
>
> Deprecated: mysql_connect(): The mysql extension is deprecated and will be
> removed in the future: use mysqli or PDO instead in
> /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php on
> line 365
>
> Warning: session_start(): Cannot send session cookie - headers already
> sent by (output started at
> /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php:365)
> in /home/darulshefaa/public_html/include/core/inc_environment_global.php on
> line 100
>
> Warning: session_start(): Cannot send session cache limiter - headers
> already sent (output started at
> /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php:365)
> in /home/darulshefaa/public_html/include/core/inc_environment_global.php on
> line 100
>
> Warning: Cannot modify header information - headers already sent by
> (output started at
> /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php:365)
> in /home/darulshefaa/public_html/index.php on line 140
>
> Warning: Cannot modify header information - headers already sent by
> (output started at
> /home/darulshefaa/public_html/classes/adodb/drivers/adodb-mysql.inc.php:365)
> in /home/darulshefaa/public_html/index.php on line 298
>
> I understood it is not compatible with php 5
>
> any help for that please?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/care2x/care2x/issues/19>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEVbMpWzx7lv5aqqh6YfHUB0jhLw8KOXks5qMMdkgaJpZM4I3ACq>
> .
>



-- 
:: Sovello Hildebrand Mgani ::



--If you teach man to fish, you'll feed him a lifetime--

**Comment by timschofield** [comment]
You need to open the file include/core/inc_init_main.php and near the bottom you will see the line:

$ErrorLevel = E_ALL && ~E_NOTICE && ~E_WARNING;

You need to change that to read:

$ErrorLevel = E_ALL && ~E_NOTICE && ~E_WARNING && ~E_DEPRECATED;

That should fix your problem.

Thanks
Tim

**Comment by timschofield** [comment]
Please note: The latest version of care2x is compatible with PHP5 and PHP7. As far as I am aware no PHP7 specific functionality has been included, and I run it on both php5 and php7 machines.

Tim

**Comment by timschofield** [comment]
Now I am properly awake this intrigues me :)

What version are you using here? You should use https://github.com/care2x/care2x/archive/master.zip but this version shouldn't give you that error whatever PHP you are using.

**Comment by extraserve** [comment]
my current php version is: 5.6.22

on this page: 
http://darulshefaa.com/hims/index.php

I receive that error before Im redirected to setup page

Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in /home/darulshefaa/public_html/hims/classes/adodb/drivers/adodb-mysqli.inc.php on line 140


then I receive this errors on isntalltion:
	PHP Database Extension is not loaded
	Cannot create ADODB connection of type

help please

**Comment by timschofield** [comment]
Do you have the php5-mysql extension loaded? The installer appears to say you haven't

Tim

**Comment by extraserve** [comment]
how to load it by cpanel?
thanx

**Comment by timschofield** [comment]
You need to speak to your hosting provider and get them to check if it is loaded.

Can you confirm you are using the version I linked to earlier?

**Comment by extraserve** [comment]
yes i have uploaded the version:

https://github.com/care2x/care2x/archive/master.zip

and errors start from here anf before referring to installation page:

http://darulshefaa.com/darulshefaa/index.php

error:
Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in /home/darulshefaa/public_html/darulshefaa/classes/adodb/drivers/adodb-mysqli.inc.php on line 140

then it refers to:
http://darulshefaa.com/darulshefaa/installer/install.php?restart_installer=true
with th error

i think i have to manually edit file: darulshefaa.com/darulshefaa/include/core/inc_init_main.php

is there amanual for installation of that version?
thanx

**Comment by timschofield** [comment]
Check that the database user and password are correctly setup in that file (darulshefaa.com/darulshefaa/include/core/inc_init_main.php)

**Comment by extraserve** [comment]
changed these lines now:

$dbname='darulshe_hims;
$dbusername='darulshe_main';
$dbpassword='TKylLW^=e)]Q';
$dbhost='localhost';
$main_domain='darulshefaa.com/darulshefaa/';
$photoserver_ip='darulshefaa.com/darulshefaa/';
$httprotocol='http';

and left these:

$dbtype='mysqli';
$timezone = 'Africa/cairo';
# First key used for simple chaining protection of scripts
$key='9.1416706867656E+27';

# Second key used for accessing modules
$key_2level='1.8072936914435E+28';

# 3rd key for encrypting cookie information
$key_login='2.0810631007321E+25';

thanx

**Comment by extraserve** [comment]
and still that error:

Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'darulshe_main'@'localhost' (using password: YES) in /home/darulshefaa/public_html/darulshefaa/classes/adodb/drivers/adodb-mysqli.inc.php on line 140

**Comment by timschofield** [comment]
Did you make this change I mentioned earlier in inc_init_main.php?

$ErrorLevel = E_ALL && ~E_NOTICE && ~E_WARNING && ~E_DEPRECATED;

**Comment by extraserve** [comment]
I did now

**Comment by extraserve** [comment]
and same errors found

**Comment by timschofield** [comment]
That seems strange, because when I look at http://darulshefaa.com/index.php it is giving E_DEPRECATED and E_WARNING errors which that should stop

**Comment by extraserve** [comment]
no Im not talking about this link

Im talking about that:

http://darulshefaa.com/darulshefaa

**Comment by extraserve** [comment]
I can even change it for this if you want

**Comment by timschofield** [comment]
You have two versions installed?

**Comment by extraserve** [comment]
now I have deleted everything
and uploading
 https://github.com/care2x/care2x/archive/master.zip

**Comment by extraserve** [comment]
now i have deleted every thing
upladed the mentioned file:

https://github.com/care2x/care2x/archive/master.zip

to http://www.darulshefaa.com/hims

on running: http://www.darulshefaa.com/hims/index.php after changing the inc_init_main.php file:

errors found: Notice: Undefined variable: ErrorLevel in /home/darulshefaa/public_html/hims/index.php on line 96

Notice: Undefined index: language_single in /home/darulshefaa/public_html/hims/index.php on line 191

and referred to installer

finished with there errors:
	PHP Database Extension is not loaded
	Cannot create ADODB connection of type
	Can not write to /home/darulshefaa/public_html/hims/cache!

thanx

**Comment by extraserve** [comment]
Hello

**Comment by extraserve** [comment]
Help please

**Comment by sovello** [comment]
extraserve,
for this error you need to create the called cache under
/home/darulshefaa/public_html/hims



2016-06-16 19:47 GMT+03:00 extraserve <notifications@github.com>:

> Help please
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/care2x/care2x/issues/19#issuecomment-226544369>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEVbMoPoiirUb5M4Y3ByqYQPdx31295Lks5qMX47gaJpZM4I3ACq>
> .
>



-- 
:: Sovello Hildebrand Mgani ::



--If you teach man to fish, you'll feed him a lifetime--

**Comment by extraserve** [comment]
now everthing is going ok until this error appears

Install Database Schema	 

	Error running SQL query: 
-- -- Dumping data for table care_department -- INSERT INTO care_department VALUES (1, 'pr', '2', 'Public Relations', 'PR', 'Press Relations', 'LDPressRelations', '', '0', '0', '1', '1', '0', '1', '0', '0', '', '', '0', '0', NULL, '', '', '', '', '', '', 00000000000000, '', 00000000000000, '','')
Incorrect integer value: '' for column 'is_pharmacy' at row 1
 
Restart Installation

**Comment by timschofield** [comment]
Can you start a fresh thread on here when you get a new issue, closing a previous one once that is solved. 

Also don't use multiple installations.

This makes it much easier to follow what is going on, and so to help you. This no longer has anything to do with the subject title.

Tim
