### ISSUE TITLE
error on installation 

### ISSUE THREAD

**Issue by extraserve** [care2x/care2x#20]
hello there
Im installing the master version on my server
on installing it this error appears at the last stage:

Install Database Schema	 

	Error running SQL query: 
-- -- Dumping data for table care_department -- INSERT INTO care_department VALUES (1, 'pr', '2', 'Public Relations', 'PR', 'Press Relations', 'LDPressRelations', '', '0', '0', '1', '1', '0', '1', '0', '0', '', '', '0', '0', NULL, '', '', '', '', '', '', 00000000000000, '', 00000000000000, '','')
Incorrect integer value: '' for column 'is_pharmacy' at row 1
 
Restart Installation

and installation process stopped

help please?

**Comment by timschofield** [comment]
Ok, this must be an sql-mode issue with mysql as it accepts that on this server. I have uploaded a new DB to github (installer/db/sql/mysqli_dump.sql). Download  it and try again.

I would delete the old database before re-installing just to be on the safe side.

Tim

**Comment by extraserve** [comment]
Cannot create Administrator user: Field 'dept_nr' doesn't have a default value

**Comment by extraserve** [comment]
Create Administrator User	 

	Completed optional database table installation.
	Cannot create Administrator user: Field 'dept_nr' doesn't have a default value

**Comment by extraserve** [comment]
hello

**Comment by extraserve** [comment]
answer please?

**Comment by extraserve** [comment]
hello

**Comment by sovello** [comment]
Do you still experience problems @extraserve?

**Comment by extraserve** [comment]
Yes still there are problems
Help please
