### ISSUE TITLE
error on end of installation

### ISSUE THREAD

**Issue by extraserve** [care2x/care2x#21]
hello there
after uploading (installer/db/sql/mysqli_dump.sql). and deleting the old installation and reinstalling the care2x
that error appeared on the end of installation process:

Create Administrator User

Completed optional database table installation.
Cannot create Administrator user: Field 'dept_nr' doesn't have a default value

also that error appeared at the beginning of installation:

Notice: Undefined variable: ErrorLevel in /home/darulshefaa/public_html/sys/index.php on line 96

Notice: Undefined index: language_single in /home/darulshefaa/public_html/sys/index.php on line 191

thanx

**Comment by extraserve** [comment]
![image](https://cloud.githubusercontent.com/assets/19966370/16251118/b66a76a2-3823-11e6-8c1f-05a05da006d1.png)

**Comment by timschofield** [comment]
I have fixed this now in the main repository.

Thanks
Tim

**Comment by extraserve** [comment]
How to fix it now?

**Comment by extraserve** [comment]
now this error:

Create Administrator User

Completed optional database table installation.
Cannot create Administrator user: Field 'dept_nr' doesn't have a default value

**Comment by timschofield** [comment]
The push hadn't worked but I have corrected that now. There are two files you need:

installer/actions/CreateAdmin.php and installer/db/sql/mysqli_dump.sql

Tim

**Comment by extraserve** [comment]
ok 
now I have deleted old files
downloading https://github.com/care2x/care2x/archive/master.zip

starting new installation

and will let you know

thanx alot

**Comment by extraserve** [comment]
did
removed all old files and database
uploaded fresh files
installed it

installation finished successfully

on opening homepage:
http://www.darulshefaa.com/sys/index.php

that error appeared
Notice: Undefined variable: ErrorLevel in /home/darulshefaa/public_html/sys/index.php on line 96

Notice: Undefined variable: ErrorLevel in /home/darulshefaa/public_html/sys/index.php on line 96

Warning: Cannot modify header information - headers already sent by (output started at /home/darulshefaa/public_html/sys/index.php:96) in /home/darulshefaa/public_html/sys/index.php on line 299

help please

**Comment by timschofield** [comment]
Should be fixed if you download the main index.php from the root
BTW your PHP version is set to output warnings and notices to the browser rather than the log file. This is a potential security issue which you should report to your hosting company.

Thanks
Tim

**Comment by extraserve** [comment]
thanx
it is worked now
