### ISSUE TITLE
error after installation on homepage

### ISSUE THREAD

**Issue by extraserve** [care2x/care2x#22]
installation finished successfully

on opening homepage:
http://www.darulshefaa.com/sys/index.php

that error appeared
Notice: Undefined variable: ErrorLevel in /home/darulshefaa/public_html/sys/index.php on line 96

Notice: Undefined variable: ErrorLevel in /home/darulshefaa/public_html/sys/index.php on line 96

Warning: Cannot modify header information - headers already sent by (output started at /home/darulshefaa/public_html/sys/index.php:96) in /home/darulshefaa/public_html/sys/index.php on line 299

help please

**Comment by extraserve** [comment]
help please?

**Comment by sovello** [comment]
Do you have a Skype contact? Check with me SkypeID: sovellohp

**Comment by extraserve** [comment]
no
gmail whatsupp and facebook

facebook: https://www.facebook.com/drmohamdeid
gmail: extraserve@gmail.com
whatsupp: 00201112229919

thanx alot

**Comment by extraserve** [comment]
added you to skype
