### ISSUE TITLE
list access permisson error

### ISSUE THREAD

**Issue by extraserve** [care2x/care2x#23]
hello there
I have aproblem on clicking on list access permession tab in the system admin dep:

Fatal error: Call to undefined function Access() in /home/darulshefaa/public_html/sys/modules/system_admin/edv_user_access_list.php on line 49

also the pharmacy and products not appearing in the main menu

test here:

http://www.darulshefaa.com/sys/index.php

user: admin
pass: admin

thanx

**Comment by extraserve** [comment]
he requested URL /sys/modules/pharmacy_tz/pharmacy_tz_pass.php was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by timschofield** [comment]
I have uploaded a new modules/system_admin/edv_user_access_list.php which corrects the list access bug.

The pharmacy module was never part of main line care2x and has been removed. This functionality should be part of the ERP not the HIS.

Tim

**Comment by extraserve** [comment]
done
now the following errors appear on system admin / Access Permissions
on clicking tabs:

users/creat role:
 Fatal error: Call to undefined function Access() in /home/darulshefaa/public_html/sys/modules/system_admin/edv_user_role_edit.php on line 25

GUI /Add new type of currency
Fatal error: Call to undefined function Core() in /home/darulshefaa/public_html/sys/modules/system_admin/edv_system_format_currency_add.php on line 18

OR administration/Create
Fatal error: Call to a member function getAllMedical() on string in /home/darulshefaa/public_html/sys/modules/or_admin/or_new.php on line 134

OR administration/List and configure
Fatal error: Call to a member function AllORInfo() on string in /home/darulshefaa/public_html/sys/modules/or_admin/or_list_config.php on line 31

thanx
