### ISSUE TITLE
some list access errors

### ISSUE THREAD

**Issue by extraserve** [care2x/care2x#24]
hello there

the following errors appear on system admin / Access Permissions
on clicking tabs:

users/creat role:
 Fatal error: Call to undefined function Access() in /home/darulshefaa/public_html/sys/modules/system_admin/edv_user_role_edit.php on line 25

GUI /Add new type of currency
Fatal error: Call to undefined function Core() in /home/darulshefaa/public_html/sys/modules/system_admin/edv_system_format_currency_add.php on line 18

OR administration/Create
Fatal error: Call to a member function getAllMedical() on string in /home/darulshefaa/public_html/sys/modules/or_admin/or_new.php on line 134

OR administration/List and configure
Fatal error: Call to a member function AllORInfo() on string in /home/darulshefaa/public_html/sys/modules/or_admin/or_list_config.php on line 31

thanx

**Comment by timschofield** [comment]
These are fixed in the master repository. You need the files listed in your original post
